AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
Resources:
  ModelHubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
  Handler: lambda_handler.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      AutoPublishAlias: prod
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET

  ModelHubApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowHeaders:
          - '*'
        AllowOrigins:
          - '*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ModelHubApi}.execute-api.${AWS::Region}.amazonaws.com/"
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ModelHubFunction.Arn